name: CI-CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - name: Obtendo o código
      uses: actions/checkout@v3
      
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PWD}}
        
    - name: Construção da imagem Docker worker
      uses: docker/build-push-action@v5.3.0
      with: 
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          kardim22/kube-news:v1
          kardim22/kube-news:latest  

  
