name: CI-CD

on:
  push:
   branches: ["main"]

jobs:
  CI:
   runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4.1.4
  - name: Construção da imagem Docker
  - uses: docker/build-push-action@v5.3.0
  with:
    context: ./src
    file: ./src/Dockerfile
    push: true
    tags: ricardoribeiro/Live-kube-news:v1
          ricardoribeiro/Live-kube-news:latest

          
  
